Fix a TypeError in http upload exception handling
When http status is not ok, body is returned as byte and need to be
decoded before specific handling:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dput/uploaders/http.py", line
114, in upload_file
    if "\n" in error_message:
TypeError: a bytes-like object is required, not 'str'

Use response charset or utf-8 to decode the response.